measurementID: measurement-2023-22-11
serverSideClusterName: kind-server-side
clientSideClusterName: kind-client-side
metricsAggregatorAddress: agregator
pairs:
  - serverNodeName: server-side-worker
    clientNodeName: client-side-worker
    serverIP: 172.18.0.3
    serverPort: 1501
    interval: 50
    duration: 5
#  - serverNode: serverNode2
#    clientNode: clientNode2
#    serverIP: 20.20.20.20
#    serverPort: 2138
#    interval: 50
#    duration: 20