measurementID: measurement-2023-22-11
serverSide: kind-server-side
clientSide: kind-client-side
metricsAggregator: agregator
pairs:
  - serverNode: server-side-worker
    clientNode: client-side-work
    serverIP: 172.18.0.3
    serverPort: 1501
    interval: 50
    duration: 10
#  - serverNode: serverNode2
#    clientNode: clientNode2
#    serverIP: 20.20.20.20
#    serverPort: 2138
#    interval: 50
#    duration: 20